keymanapp/shared-sites

_common/MarkdownHost.php
This adds a `showmenu` keyword for processing Markdown files. If false, the top menu links (like on keyman.com) won't be displayed. I intend to use these on some keyman.com test pages.
To use this keyword, the corresponding mdhost.php in the sites repo would use
```php
head([
'title' => $md->PageTitle(),
'css' => ['template.css','prism.css'],
'showMenu' => $md->ShowMenu(),
'js' => ['prism.js']
]);
```
=> chore: Add showmenu keyword for Markdown header

_common/KeymanHosts.php, _common/KeymanSentry.php
Needed for migrating from IIS to Apache
@tim-eves noticed trying to deploy the staging branch of api.keyman.com that the TIER wasn't getting set.
This follows the pattern from https://github.com/keymanapp/api.keyman.com/pull/192/files#diff-5cf5a0aa05c936b7b84e5e8ab31cfde3ac0322b20bf29bce9c9319c8ee2c231bR13
=> fix: Use getenv() instead of _SERVER vars

_common/docker.inc.sh
This adds the `--add-host` parameter as needed on Linux Docker Desktop.
Previously used on 
https://github.com/keymanapp/website-local-proxy/blob/cc780c20dbc647af02bf184a136eed7b46f44d74/build.sh#L50-L61
=> fix: Use --add-host parameter on Linux host

_common/KeymanHosts.php
This one might warrant more investigation
afaict, the JS calls in keymanweb.com couldn't get assets from host.docker.internal, while s.keyman.com.localhost worked.
=> fix: Use s.keyman.localhost

_common/KeymanHosts.php
Follow-on to #9 and fixes Sentry crash
https://keyman.sentry.io/issues/4695625860/?notification_uuid=f4c253f3-8817-4bb2-8a88-0bda0a9f987a&project=5983515&referrer=weekly_report on l. 116
Some of the references changing $site_suffix to a property got missed.
=> fix: More references to site_suffix

_common/MarkdownHost.php
If we don't have a `---\ntitle: ...\n---` section, then we should instead search for the first heading in the document, rather than just having 'Untitled page'.
This is helpful for generated documentation where we might not have the heading available, e.g. with keymanapp/keyman#10839.
=> chore: support hash headers in Markdown parser

bootstrap.inc.sh
Fixes: #18.
The bootstrap.inc.sh shell script lacked proper quotes around a variable expansion, causing it to fail when using paths that included spaces.
=> fix: bootstrap path-handling

_common/docker.inc.sh
Apologies that we didn't catch this one at the same time as #19.  Same underlying cause, too, but we hadn't made it as far at the time due to the looping bootstrap issue.
=> fix: add path-escaping to start_docker_container

_common/docker.inc.sh
Modifying bootstrapper for keymanapp/keyman.com#470 to pass an optional parameter `$BUILDER_CONFIGURATION`.
If it's debug, we can then have init-container.sh skip steps like generating CDN
Each website's build.sh can then pass `$BUILDER_CONFIGURATION`  like
```bash
builder_run_action start      start_docker_container $KEYMAN_IMAGE_NAME $KEYMAN_CONTAINER_NAME $KEYMAN_CONTAINER_DESC $HOST_KEYMAN_COM $PORT_KEYMAN_COM $BUILDER_CONFIGURATION
```
=> Pass optional `$BUILDER_CONFIGURATION` to `init-container.sh`

_common/docker.inc.sh
This will allow, for example, .htaccess directives based on the existence of the _control/debug file, so we know if we have built in debug mode or not, for example:
```
<IfFile /var/www/html/_control/debug>
... add extra logging
</IfFile>
```
_control/debug should be added to .gitignore on all sites.
=> chore: support flag file _control/debug

_common/KeymanSentry.php
Addresses keymanapp/keyman.com#476 in parsing tier.txt to determine Tier Test in CI runs.
Alternatively, I could check the environ var `KEYMANHOSTS_TIER`
https://github.com/keymanapp/keyman.com/blob/03025d8d5f9843e1ddaca205de059aaa794cf115/.github/workflows/ci.yml#L10
=> fix: Account for TIER_TEST on CI runs

_common/MarkdownHost.php
In preparation for keymanapp/keyman.com#383 of adding metadata description content headers for improving SEO.
This adds an optional page description field via PHP or HTML.
When a PHP file includes a description:
```php
head([
'title' => 'Features | Keyman for Windows ' . $stable_version,
'description' => 'Keyman for Windows Features',
...
]);
```
or when a Markdown file includes a description:
```yml
---
title: ....
description: ...
---
```
this will allow us to write HTML header info
```html
<meta name="description" content="....">
```
=> feat: Add optional 'description' field for meta description content 📓

_common/docker.inc.sh
Follows #38 
This fixes the BASH warning 
> _common/docker.inc.sh: line 76: [: =~: binary operator expected
=> fix BASH warning of binary operator

_common/GFMAlerts.php, _common/MarkdownHost.php
Hello! I tried updating this branch with no success. It was meant for one file only. Thank you!
This PR is ready for review.
=> feat: alerts continue and complete

_common/GFMAlerts.php
The code paths when a normal blockquote was encountered were not quite right. Also tidied up a few other bits and pieces for robustness.
Fixes: #49
Fixes: HELP-KEYMAN-COM-DH8
=> fix: crash in GFMAlerts when falling back to blockquote

LICENSE, _common/GFMAlerts.php
Fixes: keymanapp/help.keyman.com#1791
Once this is merged and applied to help.keyman.com (in keymanapp/help.keyman.com#1799), we need to bring back the deleted anchor text that is in keymanapp/help.keyman.com#1755.
=> fix: use ParsedownExtra as base class for GFMAlerts

_common/KeymanVersion.php, bootstrap.inc.sh
From [keymanapp/keyman.com#428
](https://github.com/keymanapp/keyman.com/pull/428#issue-2135543607)
> Note: this file KeymanVersion.php is a prime candidate to be moved to shared-sites as a future task.
This adds KeymanVersion.php to shared-sites.
Also, updates KeymanVersion to 18.0 beta and Unicode 16.0.
To merge when 18.0 beta is released.
=> fix: Migrate KeymanVersion.php, update to 18.0 beta and Unicode 16.0

_common/KeymanHosts.php
For local environment, we need to use host.docker.internal as the hostname, with corresponding ports, in order for the sites in their containers be able to communicate with each other. This adds `$SERVER_keyman_com` variables etc to the `KeymanHosts` class, in preparation for fixing this across each of the sites.
This is also groundwork for allowing the various containers in the production and staging environments to communicate with each other directly, rather than going via cloudflare, which should improve performance and reduce traffic on the cluster. This change will be implemented in a follow-up PR.
=> fix: make server-side hostnames available through `KeymanHosts`

bootstrap.inc.sh
This addresses a situation where a network glitch can cause a single file in the bootstrap to fail to download, but the bootstrap itself would continue. This tended to lead to strange site issues with missing files, which can be hard to trace.
Fixes: #58
=> fix: fail on bootstrap download error

.github/workflows/deploy-release.yml
This workflow is triggered on release events and updates the BOOTSTRAP_VERSION in the build.sh files of dependent repositories, and creates a pull request on each of the repositories with the updated version.
=> feat: trigger PR on dependent websites when release created

.github/workflows/deploy-release.yml
Ref: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#granting-additional-permissions
=> chore: use keyman-server token for release action

bootstrap.inc.sh
Handle GitHub or network instability with 5 retries on bootstrap downloads (except for the single bootstrap.inc.sh initially sourced on first use), and deal with failure by removing .bootstrap-version, so that bootstrap is forced again on next run.
This should hopefully make most deployments and CI runs self-healing as the network instability resolves, and in many cases hopefully the 5 retries will be sufficient to complete deployment/CI in one go.
Sample run with faked missing file "xassets" instead of "assets":
```
$ ./build.sh stop
[bootstrap] Bootstrap required
[bootstrap] Bootstrap starting
[bootstrap] Downloading bootstrap registry to /d/Projects/keyman/sites/help.keyman.com/resources/.bootstrap-registry
[bootstrap] Downloading _common files
[bootstrap]   Downloading …
```
=> maint: add bootstrap resilience

bootstrap.inc.sh
The function _bootstrap_try_multiple_times must be declared before any top-level code that may try and call it is executed.
=> fix: move bootstrap retry above call in bash script

.github/workflows/deploy-release.yml, _common/docker.inc.sh, build.sh, sites.inc.sh
./build.sh now available to run common commands across all site repos:
* `clone`:     Clone keyman website repositories
* `pull`:      Switch to master and pull latest changes to keyman website repositories, DELETES MERGED BRANCHES
* `configure`: Configure keyman website repositories
* `clean`:     Clean keyman website repositories
* `build`:     Build docker images for keyman website repositories
* `start`:     Start Docker containers for keyman website repositories
* `stop`:      Stop Docker containers for keyman website repositories
* `test`:      Test keyman website repositories in Docker
Note that `start` action in docker.inc.sh has been tweaked to be more resilient/idempotent -- you can run it without running build first, and now it won't error if the site is already started.
Fixes: …
=> feat: one script to control all repos
